### ISSUE TITLE
能否添加更多gcc版本？

### ISSUE THREAD

**Issue by hyj0824** [redpanda-cpp/mingw-lite#1]
感谢作者！这个项目很好的解决了mingw-w64 build的中文本地化问题，但是很好奇它能否支持更早一点版本的gcc？我应该如何修改这些脚本来实现这一点呢？

**Comment by hyj0824** [comment]
我注意到您有开发multibranches，目前是可用的的吗？还需要完成哪些工作？

**Comment by hyj0824** [comment]
我注意到您有开发multibranches，目前是可用的的吗？还需要完成哪些工作？

**Comment by hyj0824** [comment]
我注意到您有开发multibranches，目前是可用的的吗？还需要完成哪些工作？

**Comment by hyj0824** [comment]
我注意到您有开发multibranches，目前是可用的的吗？还需要完成哪些工作？

**Comment by hyj0824** [comment]
我注意到您有开发multibranches，目前是可用的的吗？还需要完成哪些工作？

**Comment by CyanoHao** [comment]
> 我注意到您有开发multibranches，目前是可用的的吗？

可以从 [GitHub Action](https://github.com/redpanda-cpp/mingw-lite/actions) 下载自动构建的版本，基本功能应该没什么问题，线程模型、旧版 Windows 支持等方面缺乏测试。

> 还需要完成哪些工作？

主要问题就是组合太多，需要添加自动化测试。考虑到实际困难（如控制台 API、旧版 Windows），至少也需要半自动测试。

**Comment by hyj0824** [comment]
我已收到！我会尽快查阅！

**Comment by CyanoHao** [comment]
感谢关注。GCC <13 的版本现已从此项目迁移至 [competitive-cross-gcc](https://github.com/redpanda-cpp/competitive-cross-gcc)，如有相关移植需求可以参考彼项目。同样通过 [GitHub Action](https://github.com/redpanda-cpp/competitive-cross-gcc/actions) 自动构建，副产物包含一个 Windows 本机工具链，文件名是 `gcc-mingw64-VER.tar.zst`。

mingw-lite 最初添加旧版 GCC 是为了配合小熊猫 C++ 在教学、比赛场景减少与评测机的差异。加入之后效果并不好（只能解决语言和 C++ 标准库的问题，并不能解决 C 标准库的问题），还导致了过大的构建矩阵、难以进行自动化测试等问题。现在我决定把这一部分独立出来成为 competitive-cross-gcc 项目，通过 “在 Windows 上编译 Linux 程序” 的交叉编译工具链来达成原先的目标。而 mingw-lite 将以 GCC 13 为界线，专注于现代 GCC 在 Windows 上的移植。
